theme: jekyll-theme-architect

title: [metro-maven-jaxb2-plugin]
description: [A subproject of jaxb]

# sidebar links url
links:
  source: https://github.com/javaee/metro-maven-jaxb2-plugin
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

